### PR TITLE
Update lib.rs

### PR DESCRIPTION
**Pull request by sarathegelatocoder**
Fix typo

### CODE REVIEW

**Comment by sarathegelatocoder** [comment]
> @googlebot I signed it!

**Comment by sarathegelatocoder** [comment]
Checking status

**Comment by tiziano88** [comment]
@googlebot ping

**Comment by anghelcovici** [comment]
I've forced a rescan from googlebot, it still appears unsigned. @sarathegelatocoder, can you check what is says under "What to do if you already signed the CLA" to see if everything is as expected?

**Comment by tiziano88** [comment]
I checked offline with @sarathegelatocoder , she created the commit from the web UI and at that time her GitHub account was set to not expose her email address, so @googlebot now cannot find a CLA for that commit. If she wants to go ahead with it, @sarathegelatocoder should re-do the commit including the same email address with which she signed the CLA.

**Comment by daviddrysdale** [comment]
Looks like this was fixed independently in commit 8ea77fa2756bf0af0d1221ea32e9a7cab684dcf5

**Pull request closed without merging**
