### PR TITLE
Remove Wasm instance in WasmState

### PR DESCRIPTION
**Pull request by rbehjati**
Merges `WasmInterface` into `WasmState`. 
Ref: https://github.com/project-oak/oak/pull/1991#discussion_r617479503

### CODE REVIEW

**Comment by rbehjati** [comment]
Not sure if this is actually an improvement!

**Review by tiziano88 — APPROVED** [review]
If you figure out how to unify WasmState and WasmInterface, please feel free to do it! I got stuck last time I tried :)

**Comment by rbehjati** [comment]
Merged them into `WasmState`. Can you take another look?

**Review by tiziano88 — APPROVED** [review]
Nice!

**Pull request merged**
