### PR TITLE
Update run-cargo-tests to run benchmarks too

### LINKED ISSUE #1933: Improve benchmarking for oak functions loader
We currently have a simple benchmark test for oak_functions loader. The runner should be updated to run the benchmark as a step in the CI builds. Moreover, it is likely that we'll need more advanced benchmarking. 
See also https://github.com/project-oak/oak/pull/1925#discussion_r601739674

Related to #1919.

### PR DESCRIPTION
**Pull request by rbehjati**
Fixes #1933

### CODE REVIEW

**Review by tiziano88 — COMMENTED** [review]
Wouldn't it be much faster to just run benchmarks after (or together with) tests? Since basically everything would be already compiled in that case.

**Comment by tiziano88** [comment]
BTW it may be enough to call `cargo test --benches`

**Comment by rbehjati** [comment]
> BTW it may be enough to call `cargo test --benches`

Thanks. Changed `run-cargo-tests` to use this.

**Review by tiziano88 — APPROVED** [review]

**Comment by rbehjati** [comment]
@tiziano88 The name of the `run-cargo-tests` is changed again! Could you please make `runner (run-cargo-tests --cleanup)` an unrequired job, and later add `runner (run-cargo-tests --cleanup --benches)`?
Is there a way to exclude options from the name of the job? Or maybe use a regex or something for specifying the required jobs? (I have no idea how the specification of the required jobs is done)

**Comment by tiziano88** [comment]
Done, it's literally just a list of strings unfortunately, but that's because we are using the command itself as the step names, in principle we could do something fancier in our CI config, not sure it's worth it though

**Comment by rbehjati** [comment]
> Done, it's literally just a list of strings unfortunately, but that's because we are using the command itself as the step names, in principle we could do something fancier in our CI config, not sure it's worth it though

I see. Thanks. Maybe we could make it fancier in the future :)

**Pull request merged**
