### PR TITLE
Move rekor verification to oak_remote_attestation_verification

### PR DESCRIPTION
**Pull request by rbehjati**

### CODE REVIEW

**Comment by ipetr0v** [comment]
We currently have [`oak_remote_attestation`](https://github.com/project-oak/oak/tree/main/oak_remote_attestation) crate. Do we want to move the code there? Or we don't want to bloat it?

**Comment by rbehjati** [comment]
> We currently have [`oak_remote_attestation`](https://github.com/project-oak/oak/tree/main/oak_remote_attestation) crate. Do we want to move the code there? Or we don't want to bloat it?

I prefer keeping them separate. The main reason is that `oak_attestation_verification` is a library that will be used client side. But I think `oak_remote_attestation` is mostly server side. Right?

**Comment by rbehjati** [comment]
> `oak_remote_attestation` just contains primitives for creating attestation evidence and verifying it. It's not server related. So I think all of the verification related code can go there.

I now see that there is a verifier in `oak_remote_attestation`, but I feel like it is better to split attestation generation and attestation verification into two modules. The client code never needs to generate an attestation, right?

> And we will use this verification code on both sides: client and server (because enclaves are going to attest each other as well).

But in that case, the enclave essentially plays both the server and client roles, and will have to use both libraries, one related to each of its roles.

> For example it could have a `transparency` submodule.

I can do that. But also I am going to work on #4196. Where we sort of decided to add a top-level `claims` crate. If everything is going to go under remote attestation, then claims should go there too. WDYT?

(I am still not sure about putting everything in `oak_remote_attestation`.)

**Comment by ipetr0v** [comment]
I think we can just have a separate crate for `transparency`. I.e. the evidence verification will still be in the `oak_remote_attestation`, and the Transparent Release story will be in a separate crate.

Like `oak_transparent_release_verification`, or `oak_transparency`

**Comment by rbehjati** [comment]
> I think we can just have a separate crate for `transparency`. I.e. the evidence verification will still be in the `oak_remote_attestation`, and the Transparent Release story verification will be in a separate crate.
> 
> Like `oak_transparent_release_verification`, or `oak_transparency`

I am not entirely convinced, but I'll move this code to `oak_remote_attestation`. But if there is going to be `oak_transparency` this code, on verifying rekor log entries, in my opinion is more relevant to `oak_transparency`.

**Comment by rbehjati** [comment]
I tried moving the code to `oak_remote_attestation`, but it is `no_std`, while rekor.rs needs `std` for loading files, etc. 

```
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 25 | use std::{cmp::Ordering, str::FromStr};
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    |     ^^^ use of undeclared crate or module `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ error[E0432]: unresolved import `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║   --> oak_remote_attestation/src/tests.rs:25:5
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    |
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 25 | use std::fs;
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    |     ^^^ use of undeclared crate or module `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ error[E0433]: failed to resolve: use of undeclared crate or module `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    --> oak_remote_attestation/src/rekor.rs:185:17
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║     |
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 185 |     let parsed: std::collections::HashMap<String, LogEntry> =
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║     |                 ^^^ use of undeclared crate or module `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ error[E0433]: failed to resolve: use of undeclared crate or module `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    --> oak_remote_attestation/src/rekor.rs:311:17
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║     |
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 311 |     let parsed: std::collections::HashMap<String, LogEntry> =
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║     |                 ^^^ use of undeclared crate or module `std`
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ error[E0412]: cannot find type `String` in this scope
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║   --> oak_remote_attestation/src/rekor.rs:33:15
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    |
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║ 33 |     pub body: String,
[19:37:05 ✓:0,✗:0,⠇:2] │││ ║    |               ^^^^^^ not found in this scope
```

Is there a requirement for making the verification logic `no_std`? If so, what options do we have for loading files and manipulating strings.

**Comment by tiziano88** [comment]
Ideally the verification logic should only deal with bytes, not files. It should not care where the bytes come from. Even under std, it should not assume that a file system is available.

As for hashmap, you can use a no_std compatible one, such as https://crates.io/crates/hashbrown, or I think you could also use a btreemap instead.

**Comment by rbehjati** [comment]
> Ideally the verification logic should only deal with bytes, not files. It should not care where the bytes come from. Even under std, it should not assume that a file system is available.

The library currently uses bytes. But the tests loads testdata from file. Is is possible to use `std` only in tests?

**Comment by rbehjati** [comment]
The note on `no_std` aside, I am still not convinced about putting the verification logic in `oak_remote_attestation`. As I said before, attestation generation and attestation verification are two separate concerns. The former is done by server (or anything that has the server role), and the latter is done by a client (or anything that has the client role). If there are special cases where an entity plays both server and client roles, it does not mean that these two roles must be coupled into one crate.

The need for the decoupling is evident even in existing Java and C libraries. The ` remote_attestation` folders under `java` and `cc` folders only contains verification logic. I don't see a valid justification for mixing the server and client behaviour in case of our Rust implementation. 

I agree that since these logics are related it is better to have them closer to each other in the directory structure, but they must not be put into the same crate, which is the unit of dependency in Rust. 

Is it possible to have a directory (not a Rust crate or workspace) containing several crates in our current setup?

**Comment by ipetr0v** [comment]
> The former is done by server (or anything that has the server role), and the latter is done by a client (or anything that has the client role).

The server will also verify attestations, because we'll make enclaves attest each other to share the private key. So the verification logic needs to work inside the enclave as well.

**Comment by rbehjati** [comment]
> > The former is done by server (or anything that has the server role), and the latter is done by a client (or anything that has the client role).
> 
> The server will also verify attestations, because we'll make enclaves attest each other to share the private key. So the verification logic needs to work inside the enclave as well.

Yes. But as I said before, in that scenario the server is actually playing the client's role. Basically, the enclave will have to have two dependencies, instead of one.

**Comment by ipetr0v** [comment]
We probably can have a separate crate for verification. But it should be called `oak_remote_attestation_verification` (since we already have `oak_remote_attestation`).

Though we will have protos and all of the DICE structs be defined in the `oak_remote_attestation` crate. So oak verification crate will still need to import `oak_remote_attestation` anyway, so it doesn't prevent us from not having server logic included on the client.

**Comment by rbehjati** [comment]
I'll first give a top-level directory for remote attestation, with multiple crates in it a try. I suppose the protos can remain a separate independent subfolder there.

**Comment by rbehjati** [comment]
@ipetr0v @tiziano88 What do you think about the following structure?

```
remote_attestation/
 ├─ oak_remote_attestation/
 │  ├─ Cargo.toml (for crate oak_remote_attestation)  
 │  ├─ src/
 │  │  ├─ lib.rs
 │  │  ├─ attester.rs
 │  │  ├─ handler.rs
 │  │  ├─ ...
 ├─ oak_remote_attestation_verification/
 │  ├─ Cargo.toml (for crate oak_remote_attestation_verification)   
 │  ├─src/verifier.rs
 ├─ oak_transparency/
 │  ├─ Cargo.toml (for crate oak_transparency)   
 ├─ proto/v1/
```

**Comment by ipetr0v** [comment]
I'm mostly fine with it. But I think the original idea was to have all crates in the top level directory (though I personally prefer actually having folders with crates).

Also, what will be in the `oak_transparency` crate?

**Comment by rbehjati** [comment]
> I'm mostly fine with it. But I think the original idea was to have all crates in the top level directory (though I personally prefer actually having folders with crates).

What is the justification for having all crates in the top level directory? A middle layer will simplify naming, and make it easier to find related code. 

Either way protos that are needed in multiple crates must be given their own crates instead of being part of another crate that uses them.

> Also, what will be in the `oak_transparency` crate?

Mostly structures for claims, as in #4196. These structure will be needed also in `oak_ml_transparency`. So maybe, `ml_transparency` or `claims` has to be a top-level directory for itself. 

Or, we as a team might decide not to pick too much on what the names should be and where the files should go, and accepts whatever alternative that works :)

**Comment by rbehjati** [comment]
@ipetr0v @tiziano88 @conradgrobler What do you think about this?

My own concern is that now that paths are changed, we have to update them internally too. So it makes sense to me to spend some time and think carefully about structure.

**Comment by conradgrobler** [comment]
I personally think this strucutre is fine, but we should not change it in isolation. If we are going to change to approach to structuring the repo we should decide on a consistent approach before starting to rearrange some parts, otherwise we will end up with more parts that don't align with the overall approach.

**Comment by tiziano88** [comment]
Please don't add more nesting; as much as I also don't like it, Rust crate names live in a global namespace and having any level of nesting obfuscates this (it took weeks to fix inconsistencies in the previous nested structure, and I think some are still around). Plus, I'm trying to merge the rust workspaces, for which having all the crates at the same level may make things simpler because we can use a wildcard to refer to all of them at once.

**Comment by tiziano88** [comment]
If the point is to share the proto folder, perhaps we should consider moving all the protos to a top level folder (like cc and java), but that's a separate discussion that we should have on an issue.

**Comment by rbehjati** [comment]
> Please don't add more nesting; as much as I also don't like it, Rust crate names live in a global namespace and having any level of nesting obfuscates this (it took weeks to fix inconsistencies in the previous nested structure, and I think some are still around). Plus, I'm trying to merge the rust workspaces, for which having all the crates at the same level may make things simpler because we can use a wildcard to refer to all of them at once.

Please note that at first I had added a top-level `oak_attestation_verification`, but I got a comment about moving the rekor-related functionality to `oak_remote_attesation`. I think the only reason for that comment is that there already too many small top-level folders in the repo, and adding one more feels like a horrifying idea. But the suggested change does not make any sense to me, because, as I described above, attestation verification and attestation generation should be separate dependency units. 

Managing dependencies correctly is a lot more important than the naming and namespacing issues. 

If keeping the structure completely flat is our strategy, I can go back to having a top-level separate directory for attestation verification.

**Comment by rbehjati** [comment]
> If the point is to share the proto folder, perhaps we should consider moving all the protos to a top level folder (like cc and java), but that's a separate discussion that we should have on an issue.

The main point of this PR was to get the rekor-related logic out of oak_functions. Now the question where it should go.

**Comment by rbehjati** [comment]
> Please don't add more nesting; as much as I also don't like it.

Please note that I am not proposing a deep nesting. Just one level. We already have folders with one level of nesting, and it works fine.

**Comment by tiziano88** [comment]
The default approach should be to just have `oak_remote_attestation` and `oak_remote_attestation_verification` as top level folders, or is there a reason why that does not work?

**Comment by tiziano88** [comment]
> > Please don't add more nesting; as much as I also don't like it.
> 
> Please note that I am not proposing a deep nesting. Just one level. We already have folders with one level of nesting, and it works fine.

To clarify (since the quote was incomplete / misleading), the thing I don't like is the fact that Rust only has a flat crate namespace. In general I personally do like the nesting, but because of how Rust works, it ends up creating more problems than it solves.

**Comment by rbehjati** [comment]
> The default approach should be to just have `oak_remote_attestation` and `oak_remote_attestation_verification` as top level folders, or is there a reason why that does not work?

That works for me. And that is what I had in my first commit a week ago. Should I go back to that again?

**Comment by tiziano88** [comment]
> > The default approach should be to just have `oak_remote_attestation` and `oak_remote_attestation_verification` as top level folders, or is there a reason why that does not work?
> 
> That works for me. And that is what I had in my first commit a week ago. Should I go back to that again?

Yes -- well I'd like to hear from who proposed the nesting, in case we are missing something. I'm just reviewing the code itself in the current form, I haven't looked at how it evolved

**Comment by tiziano88** [comment]
Ok, thanks for the context, then let's go with your previous version with `oak_remote_attestation` and `oak_remote_attestation_verification` folders.

If the verification logic does not require too many additional dependencies, then merging the two crates together and using separate mods within it is not unreasonable, but if there is no agreement then let's keep them separate for now.

If anyone feels strongly about nesting and wants to discuss a different approach (instead of the flat structure), we can do that in a dedicated issue (though I personally don't think it's worth it until Rust supports namespacing in crates -- which is unlikely to happen in the short term).

**Comment by rbehjati** [comment]
> Ok, thanks for the context, then let's go with your previous version with `oak_remote_attestation` and `oak_remote_attestation_verification` folders.

Will do. 

> If the verification logic does not require too many additional dependencies, then merging the two crates together and using separate mods within it is not unreasonable, but if there is no agreement then let's keep them separate for now.

It is not so much about what is required right now, but also how it is going to grow, and where else it is going to be used.

> If anyone feels strongly about nesting and wants to discuss a different approach (instead of the flat structure), we can do that in a dedicated issue (though I personally don't think it's worth it until Rust supports namespacing in crates -- which is unlikely to happen in the short term).

I don't know what the Rust namespacing issue is. But we already have some nesting (e.g., oak_functions, and enclave_apps). In any case, I agree that our approach to structuring the repo is a separate topic.

**Comment by rbehjati** [comment]
@ipetr0v @conradgrobler @tiziano88 Does anybody care to actually approve this PR?

**Review by conradgrobler — APPROVED** [review]

**Comment by conradgrobler** [comment]
> @ipetr0v @conradgrobler @tiziano88 Does anybody care to actually approve this PR?

I didn't receive a notification that the PR was read for re-review.

**Comment by rbehjati** [comment]
> > @ipetr0v @conradgrobler @tiziano88 Does anybody care to actually approve this PR?
> 
> I didn't receive a notification that the PR was read for re-review.

Thanks :) Looks like there is not a way to re-request a review when there are only comments on the issue, and not on the modified files.

**Pull request merged**
