### PR TITLE
Update tokio version

### PR DESCRIPTION
**Pull request by mariaschett**
# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by
        [Cloudbuild](/cloudbuild.yaml)
  - [ ] I have updated [documentation](/docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Review by rbehjati — APPROVED** [review]
Thanks :)

The latest version is 1.14.0 (https://docs.rs/tokio/1.14.0/tokio/runtime/index.html). Is not it possible to use that?

`remote_attestation/rust` uses it too. Does not it need to be updated too?

**Comment by mariaschett** [comment]
Good catch, I'll try with the latest version! 

For the `remote_attestation/rust` [#2397](https://github.com/project-oak/oak/issues/2397)

**Comment by mariaschett** [comment]
```
cargo fuzz ❯ fuzzing ❯ fuzzing "loader" ❯ apply_policy ║ error: build failed
485
cargo fuzz ❯ fuzzing ❯ fuzzing "loader" ❯ apply_policy ║ Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "/workspace/oak_functions/loader/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--bin" "apply_policy"
```
unclear why fuzz fails, but it seems unrelated to the change and similar to the previous failures [here](https://github.com/project-oak/oak/actions/runs/1467451092)

**Comment by mariaschett** [comment]
Fixes [#2395](https://github.com/project-oak/oak/issues/2395).

**Pull request merged**
