### PR TITLE
runtime/storage: use BoringSSL directly

### PR DESCRIPTION
**Pull request by daviddrysdale**
Drop dependency on the Asylo wrappers for BoringSSL's AEAD
functionality.

# Checklist

- [x] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
Fixes #517.

**Comment by tiziano88** [comment]
Aren't we going to delete this code anyways? I thought we said we would either implement it as a Rust Wasm node (possibly with the addition of some new ABI methods), or as a pure-Rust pseudo-node in the Rust runtime.

**Comment by daviddrysdale** [comment]
We've discussed a range of different possibilities, but I think they're all over longer timescales.  This keeps the existing code and tests working in the meanwhile (while removing the Asylo dep).

**Comment by tiziano88** [comment]
Sure, but I don't think we will need / use the current storage in its current form for the foreseeable future, do we? So I suggest to just drop it, and we'll re-implement it properly when we have a clearer idea of how it should work. I mean, we can keep it around until it becomes the last bit of C++, but at that point we would delete it anyways, and by then we would not have used it at all (I think). The repository history will be there and may be used as reference for future implementations.

**Comment by daviddrysdale** [comment]
Possibly not long for this world (#727) but is a blocker for #709 in the meanwhile.

**Pull request merged**
