### PR TITLE
Make pseudo-Nodes use Handles not raw channel references

### PR DESCRIPTION
**Pull request by daviddrysdale**
# Checklist

- [x] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [x] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
Probably easiest to review commit-by-commit.

**Comment by tiziano88** [comment]
I just note that this seems quite a large change to write (well, that's already done now) and review (still ongoing), for code that will (hopefully) not be around for that long! Or do you expect this code to continue existing as C++ linked to the Rust runtime in the long term @daviddrysdale ?

**Comment by daviddrysdale** [comment]
This is definitely needed for #729, and is very likely needed for #724 (unless we're expecting to get three types of pseudo-Node functionality re-implemented in Rust in the very near future).

Taken commit-by-commit, it's probably not quite as big a change as it first appears (and it wasn't that big to write &ndash; under a day).  The core of it is teasing apart and moving code from `wasm_node.cc` to `oak_node.cc`, so the former is left with Wasm-specific functionality and the latter is the only place that deals with raw channel references.

**Comment by daviddrysdale** [comment]
The existing `Message` class holds a `vector` of `ChannelHalf` objects, which hold explicit memory references to channel objects (`shared_ptr<MessageChannel>`, inside some wrappers) &ndash; and these are very runtime-internal pointers

The `NodeMessage` class is supposed to be equivalent, but with a Node-relative `Handle` (`uint64_t`) in place of a pointer &ndash; it's a `Message` as seen by a Node that does not have access to the internals of the runtime.   (Each such object is also specific to a particular Node, because the `Handle` numbering space is Node-relative.)

So by moving all of the pseudo-Node code to use `NodeMessage` rather than `Message`, it should make it easier to map to an FFI boundary that uses `Handle`s for channel identification, analogously to the ABI.

**Pull request merged**
