### PR TITLE
Add empty Treehouse Oak Application

### PR DESCRIPTION
**Pull request by ipetr0v**
Ref https://github.com/project-oak/oak/issues/1795

### CODE REVIEW

**Comment by rbehjati** [comment]
Since the example is added to `experimental` can we run it using the `run-examples` command? Or it would not be possible to run it with that command anyways?

**Comment by ipetr0v** [comment]
No, only using:
```bash
cargo build --manifest-path=experimental/treehouse/application/module/Cargo.toml
```

**Comment by ipetr0v** [comment]
Ah, no
Looks like `runner` can run it without any changes:
```bash
clear; ./scripts/runner --logs run-examples --example-name=treehouse
```

**Comment by rbehjati** [comment]
Interesting!

**Pull request merged**
