### PR TITLE
builds: drop support for MacOS

### PR DESCRIPTION
**Pull request by daviddrysdale**
Remove all vestiges of support for MacOS, as it takes too much
effort to maintain.

# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by ipetr0v** [comment]
Is `ring` Rust library currently the only reason we are dropping MacOS?

**Comment by daviddrysdale** [comment]
I was also finding that the magic steps needed to get a Rust binary linked under Bazel with a C++ library underneath are rather different on MacOS than Linux, thus making the task twice as hard.

**Comment by tiziano88** [comment]
If we managed some day to have a cargo-buildable binary, would it be easy to compile under max OS? Or would `ring` still need a special treatment?

**Comment by daviddrysdale** [comment]
My guess would be that *ring* Should Just Work™ if we used Cargo as the primary build tool, so it might be worth revisiting MacOS support if/when we get to that point.

**Pull request merged**
