### PR TITLE
Rename to Untrusted Loader to Untrusted Launcher

### PR DESCRIPTION
**Pull request by jul-sh**
We've been using both terms a little interchangeably, it'd be nice to stop doing so. Untrusted Launcher differentiates it from others loaders we have, is consistent with what AMD call the VM creation process.

### CODE REVIEW

**Comment by ipetr0v** [comment]
There is also `experimental/oak_functions_loader_linux_vsock` but it's a linux wrapper for Oak runtime which runs in a TEE, so it's not a launcher.

We probably need to define how to call it at some point as well.

**Comment by jul-sh** [comment]
@ipetr0v I actually think loader might be a fine term for that specific wrapper. It's seems rather similar to the "loader" that is part of the old oak functions linux binary.

**Comment by tiziano88** [comment]
Perhaps we can call the trusted part just `oak_functions_runtime_$PLATFORM` (where `$PLATFORM` may be the VMM or something else like `linux`, even if it's not super accurate I think it will be ok), e.g.:

- `oak_functions_runtime_vanadium`
- `oak_functions_runtime_crosvm`
- `oak_functions_runtime_qemu`
- `oak_functions_runtime_linux`

And we can keep using `oak_functions_runtime` (without `$PLATFORM`) as the name of the library crate.

WDYT?

**Comment by ipetr0v** [comment]
I think we could also remove "Untrusted" from the Launcher but keep "Trusted" for the Runtime (because this would imply that the Launcher is untrusted).

But I'm also fine with just having Launcher & Runtime without trusted/untrusted.

**Comment by jul-sh** [comment]
I do think that removing untrusted from the launcher is probably a good idea. In the context of baremetal that adjective was helpful for clarity. However once #3080 and #3082 are done, the launcher it will be trusted in some deployment configurations, and untrusted in others.

**Comment by jul-sh** [comment]
It's why I didn't include that term in the new crate name introduced in this PR (though the docs etc still use it)

**Pull request merged**
