### PR TITLE
[WIP] Attempt to print stacktrack

### PR DESCRIPTION
**Pull request by anghelcovici**
As far as I can tell this *should* work if we use the right debugger go/asylo-gdb
I haven't spent to much time on that...

### CODE REVIEW

**Comment by tiziano88** [comment]
@anghelcovici is this still current?

**Comment by tiziano88** [comment]
ping, could you let me know if  should review this, or remove me from the list of reviewers? otherwise it keeps showing up in my PR dashboard

**Comment by anghelcovici** [comment]
I *think* @daviddrysdale took this a bit further. I think I created the PR before going on holiday.

**Comment by daviddrysdale** [comment]
I took it a *bit* further but failed to get something that would get a stacktrace on Travis (for #200).  My version is saved as a branch [here](https://github.com/daviddrysdale/oak/commits/archive/crash).

I think we can close this and come back to it if needed.

**Pull request closed without merging**
