### PR TITLE
kernel wrapper: pass kernel file name via env

### PR DESCRIPTION
**Pull request by jul-sh**
We'll need more versions given that the kernel now has compile time flags. It gets messy with that many features, this is easier.

### CODE REVIEW

**Comment by jul-sh** [comment]
this doesn't work, as cargo objcopy does not pass through envs

**Comment by jul-sh** [comment]
@conradgrobler do you have ideas? `cargo objcopy` is a little bit tricky to work with. 

The easiest solution would be to always rebuild the wrapper, and just overwriting the same kernel filename regardless of features.

**Comment by conradgrobler** [comment]
Another option is to not use `cargo objcopy` and split it into two steps (`cargo build` and a separate `objcopy`) assuming that `objcopy` is available.

**Comment by jul-sh** [comment]
> Another option is to not use `cargo objcopy` and split it into two steps (`cargo build` and a separate `objcopy`) assuming that `objcopy` is available.

thanks, this helped a lot. I didn't know it could be called directly

**Review by tiziano88 — APPROVED** [review]

**Review by conradgrobler — APPROVED** [review]

**Pull request merged**
