### PR TITLE
runtime: use 'confidential' rather than 'secret'

### PR DESCRIPTION
**Pull request by daviddrysdale**
# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by tiziano88** [comment]
I actually intentionally left this around; in my mind:

noun | adjective | verb
--------|-------|-----
confidentiality | secret | declassify
integrity | trusted | endorse

@aferr WDYT?

**Comment by daviddrysdale** [comment]
Oh, OK, but it seems odd/confusing to use "secret" as the adjective form of "confidentiality" when "confidential" is an adjective.

**Comment by tiziano88** [comment]
Maybe we could use "integer" ("integral"?) instead of "trusted" too :)

Anyways, let's see what @aferr thinks, I'm happy either way, from what I've seen in the literature, elements higher up the IFC lattice are still usually referred to as "more secret".

**Comment by aferr** [comment]
Using "confidential" as the adjective instead of secret makes sense to me.

It looks like [integral](https://www.google.com/search?q=integral+definition&rlz=1C5CHFA_enUS864US864&oq=integral+definition&aqs=chrome..69i57j0l7.1931j1j9&sourceid=chrome&ie=UTF-8) doesn't work. I can't think of a better word than "trusted" to go in that column/row, so maybe it is fine.

**Comment by tiziano88** [comment]
LG, thanks @aferr for your input!

**Pull request merged**
