### PR TITLE
Fetch full repo history for running the CI on GitHub

### PR DESCRIPTION
**Pull request by rbehjati**
Ref #2455

### CODE REVIEW

**Review by tiziano88 — COMMENTED** [review]
Isn't depth 1 sufficient?

**Comment by rbehjati** [comment]
> Isn't depth 1 sufficient?

If we want to implement #2455, depth 1 is not enough. Or I cannot think of a way to get the modified files in a branch if we have only depth 1. 

I was worried fetching the entire history would take very long, but in the CI steps for this PR it is 8-17 seconds, which I think is not a big overhead.

**Comment by tiziano88** [comment]
AFAICT depth 1 is exactly what we need, i.e. the latest commit? Or maybe depth 2, perhaps I'm off by one :)

**Comment by rbehjati** [comment]
How is it possible to get the list of all modified files from only the latest commit? 
What if there are more than one commit in a pull request?

**Comment by tiziano88** [comment]
Ah got it, I was assuming 1PR == 1commit, and I thought your point was that with depth=1 even the latest commit was not accessible (hence my suggestion to try with depth=2). But you are right of course, in general that's not the case. I also looked at https://docs.github.com/en/actions/learn-github-actions/contexts#github-context to see if the number of commits is available in some variable, but it does not seem to be the case. Anyways, perhaps setting depth=50 or something like that should at least limit the amount of commits to pull in especially going forward, if the history keeps growing and if e.g. we decide to vendor more crates, in which case it will grow much faster.

**Comment by rbehjati** [comment]
> Anyways, perhaps setting depth=50 or something like that should at least limit the amount of commits to pull in especially going forward, if the history keeps growing and if e.g. we decide to vendor more crates, in which case it will grow much faster.

Currently, for local use we are using the `--commits=N` flag, where we manually specify the number of commits (N). If we want to use the same flag on GitHub and set it to a constant, for instance `--commits=50` then the builds become very non-deterministic. In most cases the 50 commits would include all the changes in 40+ earlier PR merges, which would make this whole work pointless, because there will be a high chance of including a commit that changes a `.lock` file in classic oak (for instance in the PRs from dependabot), so all the steps will have to run for most crates. I think we need a way to be able to compare the changes in the branch with `main`. 

I understand your concern with the repo growing, but I don't think fetching a specific depth alone would solve the problem. I wonder if it is possible to add a step to manually fetch main, with a specified depth, so that we could run `git diff --name-only --merge-base main`. 

Anyway, based on the speedup in [this experiment](https://github.com/project-oak/oak/runs/4668299195?check_suite_focus=true), I think it is worth starting with fetching the entire repo, and later we can optimize this part.

**Comment by rbehjati** [comment]
Subsumed in #2469.

**Pull request closed without merging**
