### PR TITLE
Add EndorsedEvidence message

### PR DESCRIPTION
**Pull request by ipetr0v**
This PR adds a combined proto message that contains an Attestation Evidence and corresponding Attestation Endorsements. This message is the one that is going to be sent to the client for attestation verification.

### CODE REVIEW

**Comment by thmsbinder** [comment]
Rather than making a proto around two other protos, we could leave them separate. This would avoid the dependency between the proto definitions. There would be two methods in the host:

absl::StatusOr<oak::attestation::v1::Evidence> GetEvidence();
absl::StatusOr<oak::attestation::v1::Endorsements> GetEndorsements();

(which is upgrade friendly since it can coexist side by side with the present GetEndorsedEvidence)

WDYT?
WDYT?

**Comment by ipetr0v** [comment]
We still need to send them to the client together

**Comment by ipetr0v** [comment]
> This would avoid the dependency between the proto definitions
We could potentially have a separate file `endorsed_evidence.proto`, or we could always add 2 separate fields `evidence` and `endorsements` to all related protos

**Comment by thmsbinder** [comment]
Yes, this would already be better.

For gRPC, couldn't we just inline the two in the response when it comes to sending them?

Before:

message Response {
  AttestationBundle bundle = 1;
}

After:

message Response {
  Evidence evidence = 1;
  Endorsements endorsements = 2;
}

**Review by tiziano88 — APPROVED** [review]

**Comment by k-naliuka** [comment]
+1 to Tom, if the reason why evidence and endorsements are bundled together is the need to communicate them to the client together, then grouping them in the response message looks like the right thing to me

**Review by conradgrobler — APPROVED** [review]
I don't have a strong opinion whether this additional wrapper helps or not, so I am fine with either keeping it or abandoning it.

**Comment by tiziano88** [comment]
I think it's fine to keep them separate, and just return both in the response. I expect the verification library to accept them as separate arguments anyway

**Comment by ipetr0v** [comment]
Closing in favor of having separate `Evidence` and `Endorsements`

**Pull request closed without merging**
