### PR TITLE
Add buildconfigs for stage1, kernel, and sysimage container binaries

### PR DESCRIPTION
**Pull request by jblebrun**

### CODE REVIEW

**Comment by jblebrun** [comment]
provenance:force-run

**Review by tiziano88 — APPROVED** [review]
that was quick! thanks Jason!

**Comment by jblebrun** [comment]
Does anyone have any idea what's going on with the `stage1_cpio` and `system_image`? It looks like they both need to be run in the `container` shell. 

Both of the buildconfigs using that shell timeout after 6 hours, and the logs indicate that... nothing has happened in that time.

Example: https://github.com/project-oak/oak/actions/runs/7596249587/job/20689764940?pr=4692

**Comment by thmsbinder** [comment]
Thanks, that helps a lot!

**Review by thmsbinder — APPROVED** [review]

**Comment by tiziano88** [comment]
> Thanks, that helps a lot!

I believe those are still not working? I still see the 6 hour timeouts / error that @jblebrun mentioned. @thmsbinder any ideas what's going wrong there?

**Comment by jblebrun** [comment]
Yes, the stage1 and system image builds still seem to hang with no output. I've been experimenting with different shell configurations to see if I can figure out what's causing the problem.

**Comment by conradgrobler** [comment]
> Yes, the stage1 and system image builds still seem to hang with no output. I've been experimenting with different shell configurations to see if I can figure out what's causing the problem.

I wonder whether it might be some kind of Docker-on-Docker permission issue. Since the provenance generation runs in a Docker container it might not be able to start another docker container as part of the build.

**Comment by jblebrun** [comment]
> > Yes, the stage1 and system image builds still seem to hang with no output. I've been experimenting with different shell configurations to see if I can figure out what's causing the problem.
> 
> I wonder whether it might be some kind of Docker-on-Docker permission issue. Since the provenance generation runs in a Docker container it might not be able to start another docker container as part of the build.

**Comment by jblebrun** [comment]
> > Yes, the stage1 and system image builds still seem to hang with no output. I've been experimenting with different shell configurations to see if I can figure out what's causing the problem.
> 
> I wonder whether it might be some kind of Docker-on-Docker permission issue. Since the provenance generation runs in a Docker container it might not be able to start another docker container as part of the build.

I think this is a good hypothesis. I'm not 100% sure, but the hanging seems to occur for shells that try to include docker.

**Comment by jblebrun** [comment]
I removed the oak_containers_system_image work from this CL, and have started another CL to figure that one out.

If everyone's happy, I'll go ahead and merge this one, which gets stage1 and bzImage added to the workflow.

**Pull request merged**
