### PR TITLE
gRPC Method Added (TEEExecute)

### PR DESCRIPTION
**Pull request by pmcgrath17**
Adding a new method name (TEEExecute) to the gRPC interface.

#4265

### CODE REVIEW

**Comment by tiziano88** [comment]
Uhmm maybe I didn't think this through enough to start with, but my original idea was to rename the grpc method exposed by the oak functions untrusted side, to something more specific (in fact ideally to the same name as the micro RPC method). But perhaps that's not possible at the moment because we are sharing the service definition with other enclave applications (e.g. the ML inference one).
Let me take a closer look at this tomorrow and we can continue the discussion then.

**Comment by pmcgrath17** [comment]
So what is the status of this? Should we continue trying to change the interface names or should this be paused?

**Comment by tiziano88** [comment]
I think we can leave this aside, right?

**Comment by pmcgrath17** [comment]
Yes, closing this pull request. We can re-open this issue sometime later.

**Pull request closed without merging**
