### PR TITLE
Update Bazel to v6.2.1

### PR DESCRIPTION
**Pull request by ipetr0v**

### CODE REVIEW

**Review by tiziano88 — APPROVED** [review]

**Comment by ipetr0v** [comment]
Do we still need to run `scripts/docker_push.sh` once we update the Docker image?

**Comment by tiziano88** [comment]
yes

**Comment by ipetr0v** [comment]
cc @pmcgrath17 @andrewkvuong 
I'm updating the Bazel version.
Please run `./scripts/docker_pull` once the PR is submitted to get the new dev Docker version.

**Comment by ipetr0v** [comment]
Since we currently moved to using Nix, where do we specify the Bazel version?

And is it already version 6?

**Comment by tiziano88** [comment]
> And is it already version 6?

[yes](https://github.com/project-oak/oak/blob/9bec4565e2fb27aac67574b662665782a582f6ad/flake.nix#L137)

**Pull request closed without merging**
