### PR TITLE
Ensure Kokoro runs against dependabot PRs

### PR DESCRIPTION
**Pull request by jul-sh**
By default kokoro checks are only triggered for PRs from users that belong to the same org as the repo. Other PRs can trigger kokoro if they include a certain label. Adds this label for all dependabot PRs.

Related to https://github.com/project-oak/oak/pull/3019, hopefully this can prevent similar build breaks

### CODE REVIEW

**Review by conradgrobler — APPROVED** [review]
Once this is submitted we should test it checking that is ran for one of the rebased dependabot PRs

**Comment by jul-sh** [comment]
Looks like it's working as expected :-) 
https://github.com/project-oak/oak/pull/3023

**Comment by tiziano88** [comment]
Is it expected that kokoro removes that label once it runs?

**Comment by tiziano88** [comment]
see https://github.com/project-oak/oak/pull/3023#event-6937422422

**Comment by tiziano88** [comment]
Also, it sounds like we should make kokoro a required CI step for merging to main, should I do that? 
cc @conradgrobler @andrisaar

**Comment by conradgrobler** [comment]
yes, I think it should be required

**Pull request merged**
