### PR TITLE
Remove --benches from `./scripts/runner run-cargo-tests`

### PR DESCRIPTION
**Pull request by mariaschett**
# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by
        [Cloudbuild](/cloudbuild.yaml)
  - [ ] I have updated [documentation](/docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Review by rbehjati — APPROVED** [review]
Thanks :) 

Does the bash completion script need to be regenerated and updated too?

**Comment by mariaschett** [comment]
@rbehjati Updating the bash completion script----absolutely! Thank you! Done!

**Comment by tiziano88** [comment]
We should probably have a test that checks that the checked in completion file is up to date :) @mariaschett could you create an issue?

**Comment by mariaschett** [comment]
Done #2429.

**Pull request merged**
