### PR TITLE
Use X25519 in Hybrid Encryption

### PR DESCRIPTION
**Pull request by ipetr0v**
We currently have to use X25519 in Rust Hybrid Encryption, because BoringSSL doesn't have support for P256 in Hybrid Encryption yet.

The latest version of `hpke` v0.10.0 uses `x25519-dalek` v2.0.0-pre.1: https://github.com/rozbb/rust-hpke/blob/2867b0ae90a36f27e2c312fe741f268ad558abbd/Cargo.toml#L47

Ref https://github.com/project-oak/oak/issues/4026

### CODE REVIEW

**Review by conradgrobler — APPROVED** [review]

**Review by tiziano88 — APPROVED** [review]

**Comment by tiziano88** [comment]
For the record, Tink also uses X25519, so this seems like a safe choice: https://developers.google.com/tink/hybrid#choosing_a_key_type

**Comment by ipetr0v** [comment]
Why do we have a copy of the `curve25519-dalek` crate in third-party: https://github.com/project-oak/oak/tree/main/third_party/curve25519-dalek

**Review by pmcgrath17 — APPROVED** [review]
Thanks for making the change. Just to verify, is the plan to still use p256 for production?

**Comment by conradgrobler** [comment]
Those were patched versions to support using the crates with the restricted kernel. IIRC it needed to depend on a newer version of the getrandom crate to be able to build with the restricted kernel.

**Comment by ipetr0v** [comment]
> Thanks for making the change. Just to verify, is the plan to still use p256 for production?

It depends on what the crypto team will tell us. But for now we can stick with X25519.

**Comment by ipetr0v** [comment]
> Those were patched versions to support using the crates with the restricted kernel. IIRC it needed to depend on a newer version of the getrandom crate to be able to build with the restricted kernel.

Does it mean that it's now outdated and we can use the `v2.0.0-pre1` (not an `v2.0.0-rc3` one, because `hpke` uses `v2.0.0-pre1`) ?

**Comment by conradgrobler** [comment]
> Does it mean that it's now outdated and we can use the `v2.0.0-pre1` (not an `v2.0.0-rc3` one, because `hpke` uses `v2.0.0-pre1`) ?

I think this mixes two unrelated questions: I don't think the patched versions in third_party are used any more, so can be deleted.

I don't know how many bug fixes are in `v2.0.0-rc3` compared to `v2.0.0-pre1`, so it is difficult to say how important it is to use one or the other. I guess it is fine for now to use the same one as the hpke crate and then update it as soon as the hpke crate updates its dependencies.

**Pull request merged**
