### PR TITLE
Temporarily disable C++ encryption

### PR DESCRIPTION
**Pull request by ipetr0v**
This PR temporarily disables C++ encryption to allow a breaking change.

Ref https://github.com/project-oak/oak/issues/4146

### CODE REVIEW

**Comment by ipetr0v** [comment]
This is required to update internal libraries

**Comment by tiziano88** [comment]
Can you explain a bit more? Wasn't this just enabled?

**Comment by ipetr0v** [comment]
The C++ encryption was always enabled, it just didn't interact with anything on the repo.

But now, since we are preparing internal libraries for this change, they should already use C++ crypto library. But since the Enclave binary doesn't support encryption yet, we need to disable it on the client side.

**Comment by ipetr0v** [comment]
> Can you explain a bit more? Wasn't this just enabled?

Also, this PR haven't been submitted yet: https://github.com/project-oak/oak/pull/4147

And only will be submitted once internal libraries are ready.

**Pull request merged**
