### PR TITLE
Oak 736 prometheus thread

### PR DESCRIPTION
**Pull request by rbehjati**
# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by tiziano88** [comment]
Does this supersede #872 ? Is either of them ready for review? If not, perhaps mark them as "draft PR" to make it clear

**Comment by rbehjati** [comment]
Yes. This is a draft PR. How do I mark it as draft? I have added a new label. Is that what you ment?

**Comment by tiziano88** [comment]
Oh, I have never seen that label before, was it already there? I just meant to click the button on GitHub that says "convert to draft PR". And in future, when creating a new PR it gives the option of choosing between a regular or draft PR.

**Comment by rbehjati** [comment]
No, I added the label after your comment. Did not know about the draft PR. Thanks.

**Comment by tiziano88** [comment]
We do have a "WIP" (Work In Progress) label BTW, though I'm not sure when we expect to use that vs a draft PR :)

**Comment by tiziano88** [comment]
@rbehjati could you delete the draft PR label? Unless you think it can still be useful, but in that case please provide some guidelines on how you think it should be used, especially with respect to actual draft PRs or the existing WIP label. Thanks!

**Pull request closed without merging**
