### PR TITLE
Remove empty AttestationEvidence from oak containers

### PR DESCRIPTION
**Pull request by jul-sh**
Encodes the real dice attestation into the AttestationEvidence format instead.

### CODE REVIEW

**Comment by jul-sh** [comment]
Is there any dependency of AttestationEvidence left? It was deprecated in https://github.com/project-oak/oak/pull/4489. If not we should fully remove it after this PR.

**Review by conradgrobler — COMMENTED** [review]
I think this needs some synchronisation with #4655. It might be possible to directly remove the deprecated evidence after that rather than also doing this intermediate step.

**Comment by jul-sh** [comment]
> I think this needs some synchronisation with #4655. It might be possible to directly remove the deprecated evidence after that rather than also doing this intermediate step.

Okay! Will defer to @ipetr0v (since. he's working on #4667). Feel free to close this if needed.

**Comment by ipetr0v** [comment]
Should we close this, since Github repo is now read-only?

**Pull request closed without merging**
