### PR TITLE
Delete TF and IREE enclave apps and related code

### PR DESCRIPTION
**Pull request by tiziano88**
Ref #4425

### CODE REVIEW

**Comment by tiziano88** [comment]
@ipetr0v @andrisaar let me know if you think any of the things I am deleting should be kept

**Comment by andrisaar** [comment]
There goes all the hard work put into the toolchain :(

**Review by andrisaar — APPROVED** [review]

**Review by ipetr0v — APPROVED** [review]
Why are we removing the toolchain?

I thought it would be used for C++ RKernel apps in general?

**Comment by tiziano88** [comment]
> Why are we removing the toolchain?
> 
> I thought it would be used for C++ RKernel apps in general?

Several months / quarters ago we decided to only support Rust for RKernel applications.

**Pull request merged**
