### PR TITLE
Move all enclave apps to a single workspace

### LINKED ISSUE #3889: Move all enclave binaries to a separate workspace
Currently each enclave binary defines its own workspace, mainly so it can specify a custom cargo config to target Oak:

https://github.com/project-oak/oak/blob/f0424c9002d20b36fd4166034e2df872a06657e3/oak_functions_enclave_app/.cargo/config.toml#L1-L5

But in practice it should be enough to just keep the current root workspace for native compilation and testing, and just create an additional workspace for all the enclave binaries. This will also reduce duplication and make it easier to run all tests or build all binaries at once (from each respective workspace).

### PR DESCRIPTION
**Pull request by conradgrobler**
Fixes #3889

### CODE REVIEW

**Comment by tiziano88** [comment]
Can you remind me what stops us from merging even those in the main workspace? If it's just that the cargo config files need to be close to the individual crates, couldn't that be solved by just creating a subfolder (may be `enclave_apps` as you have here), but part of the main workspace? I think the main change would have to be in xtask so that it knows that those crates will have to be compiled from that subfolder. Or is the problem that even in that case, running cargo build from the root repo would try to compile the enclave apps and fail?

**Comment by conradgrobler** [comment]
That actually works in the same workspace, as long as it is built from within the project directory and the `.cargo/config.toml` is in the same direcotory or a parent.

It turns out we can even move the restricted kernel and stage 0 to the same workspace, as long as we specify a different linker script path (it seems that `ld` looks for the linker script relative to the workspace root).

**Comment by tiziano88** [comment]
I want to make sure we can keep running `cargo build` and `cargo test` from the root workspace though. Does that still work?

**Comment by conradgrobler** [comment]
It seems stage0 has linking issues when it is in the same workspace, so I will leave it out for now, but I will move everything else into a single workspace.

**Comment by tiziano88** [comment]
It's fine if we need to do something more in order to actually build those binaries correctly, but the default commands must still at least do something sensible.

**Comment by conradgrobler** [comment]
> I want to make sure we can keep running `cargo build` and `cargo test` from the root workspace though. Does that still work?

Ah, no it doesn't. I will revert the last commit.

**Comment by conradgrobler** [comment]
> It's fine if we need to do something more in order to actually build those binaries correctly, but the default commands must still at least do something sensible.

One option here is to specify the `default-members` property in the workspace, which would mean that `cargo build` or `cargo test` would only run those maked as default member. The downside is that we would have to keep remembering to update this field when we add new packages, otherwise they will not be covered by `cargo build` and `cargo test`.

**Review by tiziano88 — APPROVED** [review]

**Pull request merged**
