### PR TITLE
Update .gitignore file

### PR DESCRIPTION
**Pull request by ipetr0v**
This commit adds `.cache` to `.gitignore`.

### CODE REVIEW

**Review by tiziano88 — APPROVED** [review]
Not sure why bash history would be there

**Comment by ipetr0v** [comment]
If it's not in `.gitignore`, it will always appear in `Untracked files`

**Comment by tiziano88** [comment]
But how did it end up there?

**Comment by ipetr0v** [comment]
If wasn't specified by `.gitignore`
Do you mean that Git should automatically ignore this file?

**Comment by ipetr0v** [comment]
Ah, you mean the file?
hm, it looks like bash in the Android Docker creates it

**Comment by ipetr0v** [comment]
Removing `.bash_history`

**Review by tiziano88 — APPROVED** [review]

**Pull request merged**
