### PR TITLE
Update nix deps

### PR DESCRIPTION
**Pull request by tiziano88**

### CODE REVIEW

**Comment by tiziano88** [comment]
@conradgrobler when I update Rust version, I get weird errors related to inline assembly.

To reproduce (on this PR):

```console
$ env --chdir=stage0_bin cargo build --release
   Compiling oak_stage0_bin v0.1.0 (/home/tzn/src/oak/stage0_bin)
error: register %rbp is only available in 64-bit mode
    |
note: instantiated into assembly here
   --> <inline asm>:315:12
    |
315 |     pushq  %rbp
    |            ^^^^

error: register %rbp is only available in 64-bit mode
    |
note: instantiated into assembly here
   --> <inline asm>:317:21
    |
317 |     .cfi_offset %rbp, -16
    |                     ^

error: register %rsp is only available in 64-bit mode
    |
note: instantiated into assembly here
   --> <inline asm>:318:12
    |
318 |     movq   %rsp, %rbp
    |            ^^^^

```

Even though it is being built as x86_64. Any ideas what's happening? Or is it a compiler bug?

**Comment by tiziano88** [comment]
@andrisaar

**Comment by conradgrobler** [comment]
It does not seem to come from our assembly. Perhaps this is inline assembly generated by another dependency, such as x86_64. We have small bits of 16- and 32-bit assembly, but these sections don't include any reference to %rbp or %rsp.

**Comment by tiziano88** [comment]
Thanks, I fixed the Rust version for now, also to make it easier to update that independently of the other nix packages. We can look into the issue updating to the latest version separately.

**Review by conradgrobler — APPROVED** [review]

**Pull request merged**
