### PR TITLE
Unary proto migration

### PR DESCRIPTION
**Pull request by pmcgrath17**
Splitting up the oak_remote_attestation_noninteractive protos to enable easier support for the unary RPC interface.

### CODE REVIEW

**Comment by pmcgrath17** [comment]
Moving streaming service to its own proto file.

**Review by tiziano88 — APPROVED** [review]
Nice, thanks Patrick! Please wait for @ipetr0v to approve too, but it's great to see you got all the tests to pass already!

**Review by ipetr0v — APPROVED** [review]
Thanks!

**Comment by tiziano88** [comment]
@pmcgrath17 you should be able to merge (please make sure to squash into a single commit & merge, by using the appropriate button in the GitHub UI). Let us know if you need help with that

**Comment by tiziano88** [comment]
Note when squashing and merging, GitHub usually generates a commit message with the union of all the individual commit messages, which is not very useful; I suggest manually rewording that to something sensible

**Comment by pmcgrath17** [comment]
Pull request made. Thanks for the review @tiziano88 and @ipetr0v

**Pull request merged**
