### PR TITLE
Move Container Orchestrator Client impl to the SDK

### PR DESCRIPTION
**Pull request by jblebrun**
Ref: #4478

### CODE REVIEW

**Comment by jblebrun** [comment]
I also removed the GetCryptoContext call from Orchestrator Client, since it's covered by the crypto client. Let me know if there's a case for keeping it.

**Review by ipetr0v — APPROVED** [review]
Nice!

**Review by tiziano88 — APPROVED** [review]

**Comment by ipetr0v** [comment]
The `cargo-deny` error was fixed by @tiziano88 in https://github.com/project-oak/oak/pull/4624, so you can just rebase main

**Comment by jblebrun** [comment]
Update: GetCryptoContext can not be removed until we update some clients external to this repo.

**Pull request merged**
