### PR TITLE
Fixes #134: Upgrade Rust version to 1.36.0

### LINKED ISSUE #134: Upgrade Rust version to 1.36.0
https://github.com/project-oak/oak/blob/8006ba7014cfbdb28511053958a82217260d9a5c/Dockerfile#L27

### PR DESCRIPTION
**Pull request by hansman**

### CODE REVIEW

**Comment by tiziano88** [comment]
Thanks, looks good, I'll let @anghelcovici approve and merge.

**Comment by tiziano88** [comment]
Why was the new file not created automatically though? Even if not persisted outside of the docker image via the mount point

**Comment by hansman** [comment]
It is trying to put it in directory `/user/local/cargo` which the non-root user does not have write permissions for. When mounting the file in `scripts/docker_run` to the container the file is writable (`rwxrwxr-x 1000 1000`) inside the container.

**Comment by tiziano88** [comment]
Ah, I see. In that case, I think we should fix permissions for that folder, ideally everything should work even without any volume mount, and I think fixing that permission will allow that and also fix this particular issue. If and when we decide to cache rust dependencies then we can add the volume again. WDYT?

**Comment by hansman** [comment]
That makes sense! Let me think what is a good way to make that directory writable. The RUST/CARGO dir is set in the `Dockerfile`:

https://github.com/project-oak/oak/blob/848fc3da3c016a9e68a84d3611f36e184ab11637/Dockerfile#L17-L23

We could run a `chown` right there but we don't have the UID/GID as arguments to the `Dockerfile` anymore.

**Comment by tiziano88** [comment]
I think `chmod +rw` or something like that should do?

**Comment by hansman** [comment]
Yas, that will do!

**Pull request merged**
