### PR TITLE
scripts: exclude binary hash from diff

### PR DESCRIPTION
**Pull request by daviddrysdale**
We don't yet have a mechanism that automatically updates this hash,
so don't check it for changes in the git_check_diff script.

# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [ ] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by tiziano88** [comment]
Actually I just added this in #880, and I was about to add more user-friendly instructions on what to do when this fails (namely, run `./scripts/build_server -s rust && ./scripts/build_reproducibility_index` from within Docker).

**Comment by tiziano88** [comment]
@daviddrysdale could you try and let me know if that worked for you BTW? I'll add a script + nicer error message shortly.

**Comment by tiziano88** [comment]
(if we really find it annoying we can just downgrade this to a warning instead of failing the build, but usually CI steps that just emit warnings get ignored very quickly :) )
Maybe though we can add a separate CI step that is not required for submission?

**Comment by daviddrysdale** [comment]
So is the intent that Oak developers have to spin up Docker and run that script for every change that affects the runtime?  That seems like too much friction for the current state of the project to me.

Thinking out loud, updating the index on a post-merge trigger would seem like a better approach.  We could possibly also set up a new root branch that holds the values, so we don't end polluting the `master` timeline with lots of `Update binary hash for commit 123456` commits.

**Comment by tiziano88** [comment]
> So is the intent that Oak developers have to spin up Docker and run that script for every change that affects the runtime? That seems like too much friction for the current state of the project to me.

Either that, or we manage to get a reproducible setup that works outside of Docker (which I haven't managed so far, the hashes look different when I do that :/ ).
 
> Thinking out loud, updating the index on a post-merge trigger would seem like a better approach. We could possibly also set up a new root branch that holds the values, so we don't end polluting the `master` timeline with lots of `Update binary hash for commit 123456` commits.

Yeah nice idea of having a separate branch that gets updated based on the contents of master, similar to how we auto generate documentation, let me try that out.

**Pull request closed without merging**
