### PR TITLE
Drop C++ server code

### PR DESCRIPTION
**Pull request by daviddrysdale**
# Checklist

- [x] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [x] I have written tests that cover the code changes.
  - [x] I have checked that these tests are run by [Cloudbuild](cloudbuild.yaml)
  - [x] I have updated [documentation](docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
@ipetr0v @tiziano88 : purely an FYI at this point, to make sure no-one spends time doing duplicating something that's already done or in-progress.

Please don't look at this yet.

(Unless you're about to work on something similar, in which case it's worth checking the [commit list](https://github.com/project-oak/oak/pull/1016/commits) to see if it's got anything relevant).

**Comment by daviddrysdale** [comment]
Probably easiest to review commit-by-commit &ndash; there are various preparatory commits to set things up so that the commit which removes the C++ server code is a pure deletion.

One thing still to do: this disables the `hello_world` Docker build, I'll look into re-enabling that in parallel.

Fixes: #945, #936, #850, #916, #1002 
Obviates: #944, #875, #851, #724,
Also affects: #727, #942

**Comment by juliettepretot** [comment]
image
👀

**Comment by ipetr0v** [comment]
Goodbye C++

**Pull request merged**
