### PR TITLE
Finish set_call_unwind (And NI proof!)

### PR DESCRIPTION
**Pull request by aferr**
The proof of the last theorem is clearly a mess, though.

# Checklist

- [ ] Pull request affects core Oak functionality (e.g. runtime, SDK, ABI)
  - [ ] I have written tests that cover the code changes.
  - [ ] I have checked that these tests are run by
        [Cloudbuild](/cloudbuild.yaml)
  - [ ] I have updated [documentation](/docs/) accordingly.
  - [ ] I have raised an [issue](https://github.com/project-oak/oak/issues) to
        cover any TODOs and/or unfinished work.
- [ ] Pull request includes prototype/experimental work that is under
      construction.

### CODE REVIEW

**Review by jadephilipoom — APPROVED** [review]
LGTM! But I see only `set_call_unwind` and a couple small lemmas -- did you mean to include an NI proof, or did you mean that `set_call_unwind` is the last admitted lemma for the NI proof?

**Comment by aferr** [comment]
This WAS the last admitted theorem in the first iteration of the proof. (There are some admitted theorems in LowProjPS_Thms.v but those are not used in the main proof. That file is meant to be useful in case we adopt 
[issue 1722](https://github.com/project-oak/oak/issues/1722) )

There's still more to do with these proofs, though. There are ways to make the model better. I probably should also do more of a thorough comparison of this and the implementation again. There are also better variants of NI we could be proving.

**Comment by aferr** [comment]
Tactics and cleaner proofs would still help make the rest of the proofs easier.

**Comment by jadephilipoom** [comment]
I see. Pretty big milestone, then -- congratulations!

If you haven't found it already, you can use `Print Assumptions` to see any admits that a lemma depends on.

**Comment by aferr** [comment]
Oh nice I haven't seen that. I ran `Print Assumptions possibilistic_ni` with so much anxiety! I just got:
```
Axioms:
Parameters.p : params
Parameters.lat : Lattice level
```

which I think are reasonable, still.

**Comment by jadephilipoom** [comment]
Yep, seems like those are just parameters that you've quantified over.

**Pull request merged**
